version: '3.7'

services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - node-app

  node-app:
    build: ./node-app
    volumes:
      - /usr/src/app
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=fullcycle
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fullcycle
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
